# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baijiaxing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('xingshi', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'baijiaixng',
            },
        ),
        migrations.CreateModel(
            name='Xingming',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nane', models.CharField(max_length=256)),
                ('the_same_people', models.CharField(max_length=256)),
                ('boy_ratio', models.CharField(max_length=256)),
                ('girl_ratio', models.CharField(max_length=256)),
                ('five_elements', models.CharField(max_length=256)),
                ('three_talents', models.CharField(max_length=256)),
                ('xingshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Baijiaxing')),
            ],
            options={
                'db_table': 'xingming',
            },
        ),
    ]
